services:
  frontend:
    build:
      context: ./client
    image: pa-eq3-frontend
    container_name: pa-eq3-frontend
    ports:
      - "8081:80"

  backend:
    build:
      context: ./backend
    image: pa-eq3-backend
    container_name: pa-eq3-backend
    ports:
      - "8091:8080"
    restart: on-failure:5


volumes:
  oracle-dev-data:
