stages:
  - build
  - test

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode --errors --fail-at-end --show-version --update-snapshots"

before_script:
  - export MAVEN_OPTS="-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean install
  only:
    - main

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test
  only:
    - main