services:
  oracle-dev:
    image: oracleinanutshell/oracle-xe-11g
    ports:
      - "1521:1521"
    environment:
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_DISABLE_ASYNCH_IO=true
    volumes:
      - oracle-dev-data:/u01/app/oracle
      - ./create-dev-user.sql:/docker-entrypoint-initdb.d/create-dev-user.sql

    container_name: oracle-dev-container

volumes:
  oracle-dev-data: